---
services:
  betterbahn:
    #TODO There are no semver tagged versions https://github.com/users/l2xu/packages/container/betterbahn/versions
    image: ghcr.io/l2xu/betterbahn:latest@sha256:8e4e9a0c8059665fd366c3b98aab67defd7873fc8ba6bf309da29ec74e198658
    container_name: betterbahn
    hostname: betterbahn
    environment:
      - TZ=Europe/Berlin
    read_only: true
    user: "1000:1000"
    tmpfs:
      - /tmp
    privileged: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    network_mode: bridge
    ports:
      - "8645:3000"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
