---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.5@sha256:2deb90b0423473d8f97febced2e62b8fd898aa3eb61877bb3aa336370214c258
    container_name: open-webui
    hostname: open-webui
    env_file:
      - open-webui.env
    volumes:
      - "/docker/data/open-webui:/app/backend/data"
      - "/docker/cache/open-webui:/app/backend/data/cache"
    network_mode: bridge
    ports:
      - "3059:8080"
    restart: unless-stopped
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf

volumes:
  open-webui:
    external: true
