---
name: apprise

services:
  apprise:
    image: caronc/apprise:1.3@sha256:6b112f8f174244f4a73b8e1254c9bde1fa562a6a428010aeaff1c18bc98d2713
    container_name: apprise
    hostname: apprise
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
      - APPRISE_DEFAULT_THEME=dark
      - APPRISE_STATEFUL_MODE=simple
      - APPRISE_CONFIG_LOCK=yes
      - APPRISE_WORKER_COUNT=4
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /docker/config/apprise:/config
      - ./config/pushover.yml:/config/pushover.yml:ro
    ports:
      - "8116:8000"
    network_mode: bridge
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
