---
services:
  prometheus:
    image: prom/prometheus:v3.8.1@sha256:2b6f734e372c1b4717008f7d0a0152316aedd4d13ae17ef1e3268dbfaf68041b
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/data/prometheus:/prometheus
    network_mode: bridge
    ports:
      - "9189:9090"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
