---
services:
  prometheus:
    image: prom/prometheus:v3.9.1@sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/data/prometheus:/prometheus
    network_mode: bridge
    ports:
      - "9189:9090"
    restart: always
    extends:
      file: ../../common/docker-compose.yml
      service: logging-gelf
...
